name: Release

on:
  push:
    tags:
      - '*'

jobs:

  tag:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
